[project]
name = "advent-of-code-2025"
version = "0.1.0"
description = "Python environment for advent of code"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipython>=9.7.0",
]
